# Regenerates BuildInfo.inc with the current git commit + branch + build time so
# the running build is self-identifying (About box + APP_STATE.APP_VERSION).
# Wired as the project's pre-build step, so it runs immediately before compile.
#
# MUST exit 0 even on failure: version stamping must never break a build. The
# timestamp is always written; if git is not on PATH the hash/branch fall back
# to 'unknown' rather than aborting.

$ErrorActionPreference = 'SilentlyContinue'
try {
  $hash   = (& git -C $PSScriptRoot rev-parse --short HEAD 2>$null)
  $branch = (& git -C $PSScriptRoot rev-parse --abbrev-ref HEAD 2>$null)

  if (-not $hash)   { $hash   = 'unknown' }
  if (-not $branch) { $branch = 'unknown' }

  # A build off an uncommitted working tree is not the committed hash; flag it
  # with '+' so a stamped '669e112+' is never mistaken for a clean release build.
  if ($hash -ne 'unknown') {
    $dirty = (& git -C $PSScriptRoot status --porcelain 2>$null)
    if ($dirty) { $hash = "$hash+" }
  }

  $stamp = (Get-Date -Format 'yyyy-MM-dd HH:mm')

  $inc = "// AUTO-GENERATED by GenerateBuildInfo.ps1 (project pre-build step). Do not hand-edit.`r`n" +
         "const`r`n" +
         "  BUILD_GIT_HASH   = '$hash';`r`n" +
         "  BUILD_GIT_BRANCH = '$branch';`r`n" +
         "  BUILD_TIMESTAMP  = '$stamp';`r`n"

  # ASCII, no BOM, CRLF -- matches the existing SetupVendorPublicKey.inc.
  [System.IO.File]::WriteAllText((Join-Path $PSScriptRoot 'BuildInfo.inc'), $inc, [System.Text.Encoding]::ASCII)
} catch { }

exit 0
