[CONNECTION]
eng=Pawn
dbn=Pawn
;host=ALBERTOEIBA1737
;host=ALBERTOEIBA0D23
host=127.0.0.1
;host=192.168.1.209
;host=192.168.4.69
;host=192.168.4.65
;Server Name or IP
;host=192.168.4.53
;host=ALNotebook

;driver=Adaptive Server Anywhere 9.0
;driver=SQL Anywhere 12
;dbn=NewDB
;eng=Pawn

[PRINTERS]
POLICEREP=LBP6230dw
PAYRECEIPTPRN=LBP6230dw
POLICEREPBIN=Auto
PAYRECEIPTPRNBIN=Automatically Select
UsePaymentReceiptPrinter=Y
UseEnvelopeLabelPrinter=N
EnvelopeLabelPrinterName=LBP6230dw

[LEADS_ONLINE]
CSVPath=C:\Download\

[IMAGE_STORAGE]
ImageDirectory=F:\Images
StorageMode=FILE
[DATABASE]
IsLocalDatabase=Y
[IMAGE_BACKUP]
LastBackupDate=2026-02-11
