[CONNECTION_FB]
host=127.0.0.1
;database=PAWNDATA
;database=C:\Pawn\PAWNDATA.FDB
database=C:\ProjectsGIT\PawnPro\DB\Kendalle\PAWNDATA.FDB
user=sysdba
port=3050
charset=UTF8
password_enc=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAADzKe+0gL7EeuBEYH97wz6gQAAAACAAAAAAAQZgAAAAEAACAAAAAY8wRVLQ+9RFEcqevEehUeR9TmncSkY1oN+7pvyfL48gAAAAAOgAAAAAIAACAAAABGC+ipXaa61huQg7tz8I9TQXOytDNX2/EmfdUSsZ+rahAAAAALIEqrgDHr91YI5NfvcTl1QAAAAKwfARf9+KEcd7GG9eg3GzDTS615Ofkj/SoEGA9ZcE64UFRXZfHgahgEshJxi3aXG6U/B+SjQDuuqReVLrnOpho=

[DATABASE]
IsLocalDatabase=Y

[GOLD_PRICE]
Url=https://query1.finance.yahoo.com/v8/finance/chart/GC=F?interval=1m&range=1d
Karats=10,14,18
WeightUnit=G

[SETTINGS]
SHOWGOLDPRICE=Y

[PRINTERS]
POLICEREP=OneNote (Desktop)
PAYRECEIPTPRN=LBP6230dw
POLICEREPBIN=(Default Tray)
PAYRECEIPTPRNBIN=Auto
UsePaymentReceiptPrinter=Y
UseEnvelopeLabelPrinter=Y
EnvelopeLabelPrinterName=Fax

[LEADS_ONLINE]
CSVPath=C:\ProjectsGIT\PawnProFB\LeadsOnline\

[IMAGE_STORAGE]
ImageDirectory=F:\PawnImages
StorageMode=FILE

[IMAGE_BACKUP]
LastBackupDate=2026-07-15
LastAuditWeek=

