UPDATE TABLE_KEYS
SET LAST_KEY = COALESCE((
  SELECT MAX(CAST(TRAN_TICKET_NO AS INTEGER))
  FROM TRANSACTIONS
  WHERE TRAN_TYPE = 'P'
), 0)
WHERE TABLE_NAME = 'PawnTicketNo';

UPDATE TABLE_KEYS
SET LAST_KEY = COALESCE((
  SELECT MAX(CAST(TRAN_TICKET_NO AS INTEGER))
  FROM TRANSACTIONS
  WHERE TRAN_TYPE = 'L'
), 0)
WHERE TABLE_NAME = 'LayawayTicketNo';

SELECT *
FROM TABLE_KEYS
WHERE TABLE_NAME IN ('PawnTicketNo', 'LayawayTicketNo');
