-- Create sequences (generators)
CREATE SEQUENCE GEN_CUSTOMER_ID;
CREATE SEQUENCE GEN_CATEGORY_ID;
CREATE SEQUENCE GEN_ITEM_ID;
CREATE SEQUENCE GEN_TRANSACTION_ID;
CREATE SEQUENCE GEN_TRANSACTION_ITEM_ID;
CREATE SEQUENCE GEN_SALE_ID;

-- Categories table
CREATE TABLE CATEGORIES (
    CATEGORY_ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500)
);

-- Customers table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(200),
    ADDRESS VARCHAR(500),
    ID_TYPE VARCHAR(50),
    ID_NUMBER VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NOTES VARCHAR(1000)
);

-- Items table
CREATE TABLE ITEMS (
    ITEM_ID INTEGER NOT NULL PRIMARY KEY,
    CATEGORY_ID INTEGER REFERENCES CATEGORIES(CATEGORY_ID),
    NAME VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    SERIAL_NUMBER VARCHAR(200),
    BRAND VARCHAR(100),
    MODEL VARCHAR(100),
    CONDITION VARCHAR(50) DEFAULT 'Good',
    STATUS VARCHAR(50) DEFAULT 'Available',
    APPRAISED_VALUE NUMERIC(15,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Pawn transactions
CREATE TABLE PAWN_TRANSACTIONS (
    TRANSACTION_ID INTEGER NOT NULL PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL REFERENCES CUSTOMERS(CUSTOMER_ID),
    LOAN_AMOUNT NUMERIC(15,2) NOT NULL,
    INTEREST_RATE NUMERIC(5,2) DEFAULT 10.00,
    START_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    DUE_DATE DATE NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'Active',
    TOTAL_AMOUNT_DUE NUMERIC(15,2),
    AMOUNT_PAID NUMERIC(15,2) DEFAULT 0,
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Transaction items (items used as collateral)
CREATE TABLE TRANSACTION_ITEMS (
    TRANSACTION_ITEM_ID INTEGER NOT NULL PRIMARY KEY,
    TRANSACTION_ID INTEGER NOT NULL REFERENCES PAWN_TRANSACTIONS(TRANSACTION_ID),
    ITEM_ID INTEGER NOT NULL REFERENCES ITEMS(ITEM_ID)
);

-- Sales table
CREATE TABLE SALES (
    SALE_ID INTEGER NOT NULL PRIMARY KEY,
    ITEM_ID INTEGER NOT NULL REFERENCES ITEMS(ITEM_ID),
    CUSTOMER_ID INTEGER REFERENCES CUSTOMERS(CUSTOMER_ID),
    SALE_PRICE NUMERIC(15,2) NOT NULL,
    SALE_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    NOTES VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Triggers for auto-increment IDs
SET TERM ^ ;
CREATE TRIGGER BI_CATEGORIES FOR CATEGORIES ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.CATEGORY_ID IS NULL) THEN NEW.CATEGORY_ID = NEXT VALUE FOR GEN_CATEGORY_ID;
END^
CREATE TRIGGER BI_CUSTOMERS FOR CUSTOMERS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.CUSTOMER_ID IS NULL) THEN NEW.CUSTOMER_ID = NEXT VALUE FOR GEN_CUSTOMER_ID;
END^
CREATE TRIGGER BI_ITEMS FOR ITEMS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.ITEM_ID IS NULL) THEN NEW.ITEM_ID = NEXT VALUE FOR GEN_ITEM_ID;
END^
CREATE TRIGGER BI_PAWN_TRANSACTIONS FOR PAWN_TRANSACTIONS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.TRANSACTION_ID IS NULL) THEN NEW.TRANSACTION_ID = NEXT VALUE FOR GEN_TRANSACTION_ID;
END^
CREATE TRIGGER BI_TRANSACTION_ITEMS FOR TRANSACTION_ITEMS ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.TRANSACTION_ITEM_ID IS NULL) THEN NEW.TRANSACTION_ITEM_ID = NEXT VALUE FOR GEN_TRANSACTION_ITEM_ID;
END^
CREATE TRIGGER BI_SALES FOR SALES ACTIVE BEFORE INSERT POSITION 0
AS BEGIN
  IF (NEW.SALE_ID IS NULL) THEN NEW.SALE_ID = NEXT VALUE FOR GEN_SALE_ID;
END^
SET TERM ; ^

-- Default categories
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Electronics', 'Electronic devices and gadgets');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Jewelry', 'Gold, silver, and gemstone jewelry');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Musical Instruments', 'Guitars, keyboards, and other instruments');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Tools', 'Power tools and hand tools');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Sporting Goods', 'Sports equipment and gear');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Collectibles', 'Coins, stamps, and other collectibles');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Clothing', 'Clothing and accessories');
INSERT INTO CATEGORIES (NAME, DESCRIPTION) VALUES ('Other', 'Miscellaneous items');
COMMIT;
