/*******************************************************************************
 * PawnPro - Firebird 5 Seed Reference Data
 * ----------------------------------------
 * Run this AFTER PawnPro_DB_Firebird50_Schema.sql on a brand-new database.
 * Skip for migrating stores -- the pump brings their existing reference rows.
 *
 * Seeded:
 *   IMAGES_TYPES, ITEM_STATUS, J_GENDERS, J_METALS, J_STONE_COLORS,
 *   J_STONE_SHAPES, J_STYLES, J_TYPES, PAYMENT_TYPES, STATES,
 *   TRANSACTION_TYPES, INV_CATEGORIES, EXPORT_FORMAT,
 *   TABLE_KEYS (PawnTicketNo and LayawayTicketNo counters at 0),
 *   STORE (single row: STORE_NO='0', STORE_NAME='TEST STORE', LEADS_ONLINE_FTP_ADDRESS=ftp.leadsonline.com,
 *                      DEFAULT_WEIGHT_MEASURE_UNIT='P', SALES_TAX_PERC=7)
 ******************************************************************************/

SET NAMES UTF8;

-- J_TYPES

INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('B', 'Bracelet');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('C', 'Chain');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('E', 'Earrings');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('J', 'Joya');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('L', 'Cufflinks');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('N', 'Necklace');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('P', 'Pendant Charm');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('R', 'Ring');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('W', 'Watch');
INSERT INTO J_TYPES (J_TYPE, J_TYPE_DESC) VALUES ('X', 'Other');

-- J_STYLES

INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('B', 'Box Link');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('C', 'Cuban Link');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('D', 'Cluster');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('F', 'Figaro');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('G', 'Gucci');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('H', 'Herringbone');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('M', 'Monogram');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('N', 'Nugget');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('O', 'Solitaire');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('P', 'Band');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('R', 'Rope 1');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('S', 'Serpentim');
INSERT INTO J_STYLES (J_STYLE, J_STYLE_DESC) VALUES ('X', 'Other');

-- J_METALS

INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('P', 'Platinum');
INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('S', 'Stainless Steel');
INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('T', 'Tri-color');
INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('W', 'White Gold');
INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('X', 'Other');
INSERT INTO J_METALS (J_METAL, J_METAL_DESC) VALUES ('Y', 'Yellow Gold');

-- J_GENDERS

INSERT INTO J_GENDERS (J_GENDER, J_GENDER_DESC) VALUES ('M', 'Men''s');
INSERT INTO J_GENDERS (J_GENDER, J_GENDER_DESC) VALUES ('N', 'Not Applicable');
INSERT INTO J_GENDERS (J_GENDER, J_GENDER_DESC) VALUES ('W', 'Women''s');

-- J_STONE_SHAPES

INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('E', 'Emerald');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('H', 'Heart');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('M', 'Marquise');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('O', 'Oval');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('P', 'Pear');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('R', 'Round');
INSERT INTO J_STONE_SHAPES (J_SHAPE, J_SHAPE_DESC) VALUES ('X', 'Other');

-- J_STONE_COLORS

INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('A', 'Amber');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('B', 'Blue');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('C', 'Clear');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('G', 'Green');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('K', 'Black');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('O', 'Brown');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('P', 'Purple');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('R', 'Red/Pink');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('W', 'White');
INSERT INTO J_STONE_COLORS (J_STONE_COLOR, J_STONE_DESC) VALUES ('Y', 'Yellow');

-- STATES

INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('AK', 'Alaska');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('AL', 'Alabama');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('AR', 'Arkansas');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('AZ', 'Arizona');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('CA', 'California');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('CO', 'Colorado');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('CT', 'Connecticut');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('DC', 'District of Columbia');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('DE', 'Delaware');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('FL', 'Florida');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('GA', 'Georgia');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('HI', 'Hawaii');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('IA', 'Iowa');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('ID', 'Idaho');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('IL', 'Illinois');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('IN', 'Indiana');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('KS', 'Kansas');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('KY', 'Kentucky');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('LA', 'Louisiana');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MA', 'Massachusetts');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MD', 'Maryland');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('ME', 'Maine');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MI', 'Michigan');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MN', 'Minnesota');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MO', 'Missouri');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MS', 'Mississippi');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('MT', 'Montana');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NC', 'North Carolina');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('ND', 'North Dakota');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NE', 'Nebraska');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NH', 'New Hampshire');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NJ', 'New Jersey');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NM', 'New Mexico');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NV', 'Nevada');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('NY', 'New York');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('OH', 'Ohio');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('OK', 'Oklahoma');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('OR', 'Oregon');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('PA', 'Pennsylvania');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('RI', 'Rhode Island');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('SC', 'South Carolina');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('SD', 'South Dakota');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('TN', 'Tennessee');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('TX', 'Texas');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('UT', 'Utah');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('VA', 'Virginia');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('VT', 'Vermont');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('WA', 'Washington');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('WI', 'Wisconsin');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('WV', 'West Virginia');
INSERT INTO STATES (STATE_ABBR, STATE_NAME) VALUES ('WY', 'Wyoming');

-- ITEM_STATUS

INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('C', 'Scrap');
INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('D', 'Sold');
INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('L', 'Layaway');
INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('P', 'Pawn');
INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('R', 'Redeem');
INSERT INTO ITEM_STATUS (STATUS, STATUS_DESC) VALUES ('S', 'For Sale');

-- TRANSACTION_TYPES

INSERT INTO TRANSACTION_TYPES (TRAN_TYPE, TRAN_TYPE_DESC) VALUES ('L', 'Layaway');
INSERT INTO TRANSACTION_TYPES (TRAN_TYPE, TRAN_TYPE_DESC) VALUES ('P', 'Pawn');
INSERT INTO TRANSACTION_TYPES (TRAN_TYPE, TRAN_TYPE_DESC) VALUES ('S', 'Sale');
INSERT INTO TRANSACTION_TYPES (TRAN_TYPE, TRAN_TYPE_DESC) VALUES ('U', 'Purchase');

-- PAYMENT_TYPES

INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (1, 'Cash', '999999', 'N');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (2, 'Check', '999999', 'N');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (3, 'Money Order', '999999', 'N');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (4, 'MasterCard', '9999 9999 9999 9999', 'Y');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (5, 'Visa', '9999 9999 9999 9999', 'Y');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (6, 'America Express', '9999 9999 9999 9999', 'Y');
INSERT INTO PAYMENT_TYPES (PAY_TYPE_NO, PAYMENT_TYPE, PAYMENT_MASK, IS_CREDIT_CARD) VALUES (7, 'Discover', '9999 9999 9999 9999', 'Y');

-- IMAGES_TYPES

INSERT INTO IMAGES_TYPES (IMAGE_TYPE, IMAGE_TYPE_DESC) VALUES (1, 'Customer ID');
INSERT INTO IMAGES_TYPES (IMAGE_TYPE, IMAGE_TYPE_DESC) VALUES (2, 'Item Picture');

-- INV_CATEGORIES

INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('BRACELET');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('CHAIN');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('CUFFLINKS');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('EARRINGS');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('NECKLACE');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('OTHER');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('PENDANT/CHARM');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('RING');
INSERT INTO INV_CATEGORIES (INV_CATEGORY) VALUES ('WATCH');

-- EXPORT_FORMAT

INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ticket_type', 1, 0, 'ticket_type', 'Transaction Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('TranTicketNo', 2, 25, 'ticket_number', 'Transaction Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('TranDate', 3, 0, 'enter_date', 'Transaction Date');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ClerkName', 2, 50, 'clerk', 'Clerk Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('TranVoided', 2, 1, 'void', 'void');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('AmountRedeemDefaultDate', 0, 0, 'redeem_date', 'Redemption Date');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 25, 'ticket_number_orig', 'Original Transaction Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 4, 0, 'enter_date_orig', 'Original Transaction Date');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 2000, 'pledgor_statement', 'Pledgor Statement');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustLast', 2, 50, 'cust_nm_last', 'Customer Last Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustFirst', 2, 25, 'cust_nm_first', 'Customer First Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustMid', 2, 25, 'cust_nm_middle', 'Customer Middle Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'cust_nm_suffix', 'Customer Name Suffix');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustAddr', 2, 100, 'cust_addr1', 'Customer Address');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 100, 'cust_addr2', 'Customer Address Line 2');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustCity', 2, 50, 'cust_city', 'Customer City');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustState', 2, 25, 'cust_state', 'Customer State');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustZip', 2, 10, 'cust_zip', 'Customer Postal Code');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ClientPhone', 2, 20, 'cust_phone', 'Customer Phone');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ClientIdType', 2, 25, 'cust_id_type', 'Customer ID Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ClientIdState', 2, 2, 'cust_id_state', 'Customer ID State');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ClientIdNumber', 2, 50, 'cust_id_number', 'Customer ID Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 4, 0, 'cust_id_exp', 'Customer ID Expiration');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 4, 0, 'cust_id_issue_dt', 'Customer ID Issue Date');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 25, 'cust_id_type2', 'Customer Second ID Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 2, 'cust_id_state2', 'Customer Second ID State');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 50, 'cust_id_number2', 'Customer Second ID Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 4, 0, 'cust_id_exp2', 'Customer Second ID Expiration');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 4, 0, 'cust_id_issue_dt2', 'Customer Second ID Issue Date');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustDOB', 4, 0, 'cust_birthdate', 'Customer Date of Birth');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustWeight', 1, 0, 'cust_weight', 'Customer Weight');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustHeight', 5, 0, 'cust_height', 'Customer Height');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustEyes', 2, 10, 'cust_eye', 'Customer Eye Color');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustHair', 2, 10, 'cust_hair', 'Customer Hair Color');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustRace', 2, 20, 'cust_race', 'Customer Race');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustGender', 2, 10, 'cust_sex', 'Customer Sex');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 100, 'cust_info', 'Other Information About Customer');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CustPlaceEmply', 2, 150, 'employer_nm', 'Employer Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 100, 'employer_addr1', 'Employer Address');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 100, 'employer_addr2', 'Employer Address Line 2');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 50, 'employer_city', 'Employer City');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 25, 'employer_state', 'Employer State');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'employer_zip', 'Employer Postal Code');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 20, 'employer_phone', 'Employer Phone');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ItemSeq', 6, 25, 'item_number', 'Line Item Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('InvItemCount', 1, 0, 'item_qty', 'Item Quantity');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('InvItemBrand', 2, 50, 'item_make', 'Item Make');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('ModelNumber', 2, 50, 'item_model', 'Item Model Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('SerialNumber', 2, 50, 'item_serial', 'Item Serial Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 50, 'item_oan', 'Owner Applied Number');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'item_color', 'Item Color');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 25, 'item_condition', 'Item Condition');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('Description', 2, 250, 'item_desc', 'Item Description');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('Note', 2, 250, 'item_notes', 'Item Notes');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('1', 7, 0, 'item_category', 'Item Category');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 8, 'item_ncic', 'Item NCIC Code');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('UnitCost', 1, 0, 'item_amount', 'Amount Paid for Item');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JStyleDesc', 2, 25, 'jewelry_style', 'Jewelry Style');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JMetalDesc', 2, 10, 'jewelry_metal', 'Jewelry Metal');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('KT', 1, 0, 'jewelry_kt', 'Jewelry Metal Karat');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('Weight', 1, 0, 'jewelry_wt', 'Jewelry Weight');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'jewelry_wt_unit', 'Jewelry Unit of Weight');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('SizeLength', 2, 10, 'jewelry_size', 'Jewelry Size or Length');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('Gender', 2, 10, 'jewelry_sex', 'Jewelry Gender');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 50, 'jewelry_class_nm', 'Jewelry School Class Name');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 4, 'jewelry_class_yr', 'Jewelry School Class Year');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('StoneType1', 2, 15, 'jewelry_stone1_type', 'Primary Stone Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JStoneDesc1', 2, 10, 'jewelry_stone1_color', 'Primary Stone Color');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('StoneNumber1', 1, 0, 'jewelry_stone1_qty', 'Primary Stone Quantity');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JShapeDesc1', 2, 10, 'jewelry_stone1_shape', 'Primary Stone Shape/Cut');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CT1', 2, 10, 'jewelry_stone1_carat', 'Primary Stone Carat');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('StoneType2', 2, 15, 'jewelry_stone2_type', 'Secondary Stone Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JStoneDesc2', 2, 10, 'jewelry_stone2_color', 'Secondary Stone Color');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('StoneNumber2', 1, 0, 'jewelry_stone2_qty', 'Secondary Stone Quantity');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('JShapeDesc2', 2, 10, 'jewelry_stone2_shape', 'Secondary Stone Shape/Cut');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('CT2', 2, 10, 'jewelry_stone2_carat', 'Secondary Stone Carat');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'firearm_caliber', 'Firearm Caliber');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'firearm_type', 'Firearm Type');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 10, 'firearm_action', 'Firearm Action');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 15, 'firearm_finish', 'Firearm Finish');
INSERT INTO EXPORT_FORMAT (DATA_FIELD_NAME, DATA_FIELD_TYPE, DATA_FIELD_MAX_SIZE, DATA_FIELD_CAPTION, DATA_FIELD_DESC) VALUES ('NONE', 2, 15, 'firearm_barrel', 'Firearm Barrel');


-- TABLE_KEYS

INSERT INTO TABLE_KEYS (TABLE_NAME, LAST_KEY) VALUES ('PawnTicketNo', 0);
INSERT INTO TABLE_KEYS (TABLE_NAME, LAST_KEY) VALUES ('LayawayTicketNo', 0);

-- STORE (single row -- store admin fills the remaining fields through the app)

INSERT INTO STORE (STORE_NO, STORE_NAME, LEADS_ONLINE_FTP_ADDRESS, DEFAULT_WEIGHT_MEASURE_UNIT, SALES_TAX_PERC) VALUES ('0', 'TEST STORE', 'ftp.leadsonline.com', 'P', 7);

COMMIT;
