/*******************************************************************************
 * Default character set: UTF8
 * Server version: 5.0
 * Server version string: WI-V5.0.3.1683 Firebird 5.0
 * Database ODS: 13.1
 * Database page size: 32768
 ******************************************************************************/

/*******************************************************************************
 * Selected metadata objects
 * -------------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

/*******************************************************************************
 * Roles
 * -----
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

/* "PUBLIC" is a system role, no CREATE ROLE statement. */

/* "RDB$ADMIN" is a system role, no CREATE ROLE statement. */

GRANT RDB$ADMIN TO SYSDBA WITH ADMIN OPTION;

/*******************************************************************************
 * Tables
 * ------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE TABLE APP_STATE
(
  STATE_KEY             VARCHAR(50)  NOT NULL,
  STATE_DESC            VARCHAR(255),
  VALUE_TEXT            VARCHAR(255),
  VALUE_INT             INTEGER,
  VALUE_CURRENCY        NUMERIC(18,2),
  VALUE_DATE            TIMESTAMP,
  CONSTRAINT PK_APP_STATE PRIMARY KEY (STATE_KEY)
);

CREATE TABLE BACKUP_HISTORY
(
  BCK_ID                INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  BCK_DATE            TIMESTAMP         NOT NULL,
  BCK_PATH              VARCHAR(120) NOT NULL,
  PRIMARY KEY (BCK_ID)
);

CREATE TABLE BACKUP_SETTINGS 
(
  BACKUP_PATH                             VARCHAR(255) NOT NULL,
  AUTO_BACKUP_WHEN_CLOSE_APP              BOOLEAN         DEFAULT FALSE NOT NULL,
  BACKUP_IMAGES_PATH                      VARCHAR(255),
  CONSTRAINT ID PRIMARY KEY (BACKUP_PATH)
);

CREATE TABLE CUSTOMER 
(
  CUST_NO                           INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  CUST_FIRST                        VARCHAR(35),
  CUST_MID                             CHAR(1),
  CUST_LAST                         VARCHAR(35),
  CUST_DOB                             DATE,
  CUST_GENDER                          CHAR(1),
  CUST_RACE                            CHAR(1),
  CUST_HAIR                         VARCHAR(5),
  CUST_EYES                         VARCHAR(5),
  CUST_MARK                         VARCHAR(10),
  CUST_WEIGHT              DOUBLE PRECISION,
  CUST_HEIGHT                       VARCHAR(8),
  CUST_ADDR                         VARCHAR(55),
  CUST_APT                          VARCHAR(5),
  CUST_CITY                         VARCHAR(40),
  CUST_STATE                           CHAR(2),
  CUST_ZIP                          VARCHAR(11),
  CUST_PLACE_EMPLY                  VARCHAR(30),
  CUST_FL_DRV_LIC                   VARCHAR(20),
  CUST_ID                           VARCHAR(25),
  CUST_ID_TYPE                      VARCHAR(20),
  CUST_ID_AGENCY_STATE              VARCHAR(10),
  CUST_PH_HOME                      VARCHAR(14),
  CUST_PH_BUSINESS                  VARCHAR(14),
  CUST_PH_BEEP                      VARCHAR(14),
  CUST_PH_CELL                      VARCHAR(14),
  CUST_COMMENT                         BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  PRIMARY KEY (CUST_NO)
);

CREATE TABLE EXPORT_FILE_LOG 
(
  EXPORT_LOG_ID              INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  EXPORT_DATE              TIMESTAMP         NOT NULL,
  FILE_NAME                  VARCHAR(50) NOT NULL,
  ITEM_COUNT                 INTEGER         DEFAULT 0 NOT NULL,
  PRIMARY KEY (EXPORT_LOG_ID)
);

CREATE TABLE EXPORT_FORMAT 
(
  ID                               INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  DATA_FIELD_NAME                  VARCHAR(50) NOT NULL,
  DATA_FIELD_TYPE                 SMALLINT         NOT NULL,
  DATA_FIELD_MAX_SIZE              INTEGER         NOT NULL,
  DATA_FIELD_CAPTION               VARCHAR(50) NOT NULL,
  DATA_FIELD_DESC                  VARCHAR(200),
  PRIMARY KEY (ID)
);

CREATE TABLE EXPORT_LOG_FILE_DETAIL 
(
  ID                          INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  EXPORT_LOG_ID               INTEGER         NOT NULL,
  TRANSACTION_NO              INTEGER         NOT NULL,
  EXPORT_LINE                    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  INV_ITEM_NO                 INTEGER,
  ITEM_SEQ                    INTEGER,
  PRIMARY KEY (ID)
);

-- Tracks LeadsOnline transaction images (customer ID photos) sent once per
-- transaction; item images use IMAGES_DATA.UPLOAD_TIME instead. See
-- Schema/Migrations/PawnPro_FB5_AddExportImageSent.sql for the rationale.
CREATE TABLE EXPORT_IMAGE_SENT
(
  ID                          INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  TRANSACTION_NO              INTEGER         NOT NULL,
  IMAGES_DATA_NO              INTEGER         NOT NULL,
  UPLOAD_TIME                 TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPLOAD_FILE_NAME            VARCHAR(50),
  CONSTRAINT PK_EXPORT_IMAGE_SENT PRIMARY KEY (ID),
  CONSTRAINT UQ_EXPORT_IMAGE_SENT UNIQUE (TRANSACTION_NO, IMAGES_DATA_NO)
);

CREATE TABLE GOLD_PRICE_HISTORY
(
  PRICE_ID                     INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  PRICE_PER_OUNCE              DECIMAL(10,2) NOT NULL,
  CURRENCY                     VARCHAR(3) DEFAULT 'USD' NOT NULL,
  FETCHDATETIME              TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
  SOURCE                       VARCHAR(50) DEFAULT 'Yahoo' NOT NULL,
  API_RESPONSE                    BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  CONSTRAINT PK_GOLD_PRICE_HISTORY PRIMARY KEY (PRICE_ID)
);

CREATE TABLE IMAGES_DATA 
(
  IMAGES_DATA_NO                  INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  IMAGE_TYPE_NO                   INTEGER         NOT NULL,
  IMAG_REF_TO_ROW_NO              INTEGER         NOT NULL,
  IMAGE_DESC                      VARCHAR(125),
  IMAGE_DATA                         BLOB SUB_TYPE 0 SEGMENT SIZE 80,
  CREATED                       TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPLOAD_TIME                   TIMESTAMP,
  UPLOAD_FILE_NAME                VARCHAR(50),
  PRIMARY KEY (IMAGES_DATA_NO)
);

CREATE TABLE IMAGES_DATA_BACKUP 
(
  ID                          INTEGER         NOT NULL,
  IMAGES_DATA_NO              INTEGER,
  CONSTRAINT PK_IMAGES_DATA_BACKUP PRIMARY KEY (ID)
);

CREATE TABLE IMAGES_TYPES 
(
  IMAGE_TYPE_NO                INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  IMAGE_TYPE                   INTEGER         NOT NULL,
  IMAGE_TYPE_DESC              VARCHAR(80),
  PRIMARY KEY (IMAGE_TYPE_NO)
);

CREATE TABLE INVENTORY_ITEMS 
(
  INV_ITEM_NO                       INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_ITEM_BARCODE                  VARCHAR(30),
  INV_CAT_NO                        INTEGER         NOT NULL,
  J_TYPE                               CHAR(1),
  J_STYLE                              CHAR(1),
  J_METAL                              CHAR(1),
  INV_ITEM_COUNT                    INTEGER,
  NOTE                              VARCHAR(80),
  SIZE_LENGTH              DOUBLE PRECISION,
  WEIGHT                   DOUBLE PRECISION,
  KT                       DOUBLE PRECISION,
  CREATED                         TIMESTAMP         DEFAULT CURRENT_TIMESTAMP,
  UNIT_COST                         DECIMAL(18,2),
  UNIT_PRICE                        DECIMAL(18,2),
  INV_ITEM_STATUS                      CHAR(1) DEFAULT 'S',
  TRANSACTION_NO                    INTEGER,
  INV_ORIGINAL_ITEM_NO              INTEGER,
  INV_ITEM_BRAND                    VARCHAR(30),
  SERIAL_NUMBER                     VARCHAR(40),
  OWNER_APP_NUMBER                  VARCHAR(40),
  MODEL_NUMBER                      VARCHAR(40),
  GENDER                               CHAR(1),
  DESCRIPTION                       VARCHAR(120),
  WEIGHT_UNIT                          CHAR(1),
  PAWNED_DATE                          DATE,
  PURCHASE_DATE                        DATE,
  REDEEMED_DATE                        DATE,
  DEFAULTED_DATE                       DATE,
  MELTED_DATE                          DATE,
  FORSALE_DATE                         DATE,
  SOLD_DATE                            DATE,
  LAYAWAY_DATE                         DATE,
  PRIMARY KEY (INV_ITEM_NO)
);

CREATE TABLE INVENTORY_ITEM_STATUS_LOG 
(
  LOG_ID                           BIGINT         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_ITEM_NO                     INTEGER         NOT NULL,
  OLD_STATUS                         CHAR(1),
  NEW_STATUS                         CHAR(1) NOT NULL,
  OLD_PAWNED_DATE                    DATE,
  NEW_PAWNED_DATE                    DATE,
  OLD_PURCHASE_DATE                  DATE,
  NEW_PURCHASE_DATE                  DATE,
  OLD_REDEEMED_DATE                  DATE,
  NEW_REDEEMED_DATE                  DATE,
  OLD_DEFAULTED_DATE                 DATE,
  NEW_DEFAULTED_DATE                 DATE,
  OLD_MELTED_DATE                    DATE,
  NEW_MELTED_DATE                    DATE,
  OLD_FORSALE_DATE                   DATE,
  NEW_FORSALE_DATE                   DATE,
  OLD_SOLD_DATE                      DATE,
  NEW_SOLD_DATE                      DATE,
  OLD_LAYAWAY_DATE                   DATE,
  NEW_LAYAWAY_DATE                   DATE,
  CHANGED_BY                      VARCHAR(50),
  CHANGED_AT                    TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_INVENTORY_ITEM_STATUS_LOG PRIMARY KEY (LOG_ID)
);

CREATE TABLE INV_CATEGORIES 
(
  INV_CAT_NO                INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_CATEGORY              VARCHAR(40) NOT NULL,
  PRIMARY KEY (INV_CAT_NO)
);

CREATE TABLE ITEM_STATUS 
(
  STATUS                      CHAR(1) NOT NULL,
  STATUS_DESC              VARCHAR(30) NOT NULL,
  PRIMARY KEY (STATUS)
);

CREATE TABLE J_GENDERS 
(
  J_GENDER                      CHAR(1) NOT NULL,
  J_GENDER_DESC              VARCHAR(30) NOT NULL,
  PRIMARY KEY (J_GENDER)
);

CREATE TABLE J_METALS 
(
  J_METAL                      CHAR(1) NOT NULL,
  J_METAL_DESC              VARCHAR(30) NOT NULL,
  CUST_FIELD                BOOLEAN         DEFAULT false,
  PRIMARY KEY (J_METAL)
);

CREATE TABLE J_STONE_COLORS 
(
  J_STONE_COLOR                 CHAR(1) NOT NULL,
  J_STONE_DESC               VARCHAR(30) NOT NULL,
  CUST_FIELD                 BOOLEAN         DEFAULT false,
  PRIMARY KEY (J_STONE_COLOR)
);

CREATE TABLE J_STONE_SHAPES 
(
  J_SHAPE                      CHAR(1) NOT NULL,
  J_SHAPE_DESC              VARCHAR(30) NOT NULL,
  CUST_FIELD                BOOLEAN         DEFAULT false,
  PRIMARY KEY (J_SHAPE)
);

CREATE TABLE J_STYLES 
(
  J_STYLE                      CHAR(1) NOT NULL,
  J_STYLE_DESC              VARCHAR(30) NOT NULL,
  CUST_FIELD                BOOLEAN         DEFAULT false,
  PRIMARY KEY (J_STYLE)
);

CREATE TABLE J_TYPES 
(
  J_TYPE                      CHAR(1) NOT NULL,
  J_TYPE_DESC              VARCHAR(30) NOT NULL,
  CUST_FIELD               BOOLEAN         DEFAULT false,
  PRIMARY KEY (J_TYPE)
);

CREATE TABLE PAYMENTS 
(
  PAYMENT_NO                    INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  TRANSACTION_NO                INTEGER,
  PAY_DATE                         DATE,
  PAY_AMOUNT           DOUBLE PRECISION,
  PAY_COMMENT                      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  PAY_METHOD                   SMALLINT         DEFAULT 1,
  PAY_INTEREST         DOUBLE PRECISION,
  PAY_PRINCIPAL        DOUBLE PRECISION,
  PRINC_BALANCE        DOUBLE PRECISION,
  INTEREST_BALANCE     DOUBLE PRECISION,
  PRIMARY KEY (PAYMENT_NO)
);

CREATE TABLE PAYMENT_TYPES 
(
  PAY_TYPE_NO                 INTEGER         NOT NULL,
  PAYMENT_TYPE                VARCHAR(20) NOT NULL,
  PAYMENT_MASK                VARCHAR(25) NOT NULL,
  IS_CREDIT_CARD                 CHAR(1),
  CONSTRAINT PK_PAYMENT_TYPES PRIMARY KEY (PAY_TYPE_NO)
);

CREATE TABLE SALES_ITEMS 
(
  SALES_ITEM_NO                 INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_ITEM_NO                   INTEGER         NOT NULL,
  SALES_ITEM_DESC               VARCHAR(30) NOT NULL,
  CAT_NO                        INTEGER,
  J_TYPE                           CHAR(1),
  J_STYLE                          CHAR(1),
  J_METAL                          CHAR(1),
  J_SHAPE                          CHAR(1),
  J_STONE_COLOR                    CHAR(1),
  SALES_ITEM_COUNT              INTEGER,
  AMOUNT               DOUBLE PRECISION,
  PRIMARY KEY (SALES_ITEM_NO)
);

CREATE TABLE STATES 
(
  STATE_ABBR              VARCHAR(2),
  STATE_NAME              VARCHAR(30)
);

CREATE TABLE STONES 
(
  STONE_NO                       INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_ITEM_NO                    INTEGER         NOT NULL,
  STONE_NUMBER                   INTEGER         NOT NULL,
  STONE_SHAPE                       CHAR(1) NOT NULL,
  STONE_COLOR                       CHAR(1) NOT NULL,
  CT                    DOUBLE PRECISION,
  WT                    DOUBLE PRECISION,
  STONE_TYPE                     VARCHAR(30),
  STONE_WEIGHT_UNIT                 CHAR(1),
  PRIMARY KEY (STONE_NO)
);

CREATE TABLE STORE 
(
  STORE_NO                                 VARCHAR(10),
  STORE_NAME                               VARCHAR(55),
  STORE_ADDR                               VARCHAR(55),
  STORE_CITY_ST_ZIP                        VARCHAR(55),
  STORE_PHONE                              VARCHAR(14),
  STORE_POLICE_ID                          VARCHAR(30),
  STORE_ADJ_TOP_MARG                       INTEGER,
  STORE_NUMBER                             VARCHAR(30),
  STORE_ADJ_DETAIL_HEIGHT                  INTEGER         DEFAULT 0,
  STORE_ADJ_FOOTER_HEIGHT                  INTEGER         DEFAULT 0 NOT NULL,
  INTEREST_CALC_METHOD                     INTEGER         DEFAULT 1,
  POLICE_REPORT_TO_PRINT                   INTEGER         DEFAULT 1,
  POLICE_REPORT_LASER_COPIES               INTEGER         DEFAULT 3,
  DEFAULT_MATURITY_MONTHS                  INTEGER         DEFAULT 1,
  PAWN_DEFAULT_MONTHS                      INTEGER         DEFAULT 2,
  LEADS_STORE_ID                           VARCHAR(20),
  LEADS_ONLINE_FTP_ADDRESS                 VARCHAR(50),
  LEADS_ONLINE_USER_NAME                   VARCHAR(50),
  LEADS_ONLINE_PASSWORD                    VARCHAR(50),
  FTP_PASSIVE                              BOOLEAN         DEFAULT TRUE NOT NULL,
  PAWN_DATE_CALCULATION_BASE                  CHAR(1) DEFAULT 'D',
  DEFAULT_WEIGHT_MEASURE_UNIT                 CHAR(1),
  SALES_TAX_PERC                  DOUBLE PRECISION,
  DEFAULT_PAWN_INTERESTRATE       DOUBLE PRECISION         DEFAULT 10
);

CREATE TABLE TABLE_KEYS 
(
  TABLE_NAME                 CHAR(15) NOT NULL,
  LAST_KEY                INTEGER         DEFAULT 0 NOT NULL,
  PRIMARY KEY (TABLE_NAME)
);

CREATE TABLE TRANSACTIONS 
(
  TRANSACTION_NO                 INTEGER         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  CUST_NO                        INTEGER,
  TRAN_DATE                         DATE         DEFAULT CURRENT_DATE,
  TRAN_TICKET_NO                 VARCHAR(30),
  TRAN_COMMENT                      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
  TRAN_MATURITY                     DATE,
  TRAN_TYPE                         CHAR(1) DEFAULT 'P',
  TRAN_STATUS                       CHAR(1) DEFAULT 'A',
  TRAN_VOID_DATE               TIMESTAMP,
  TRAN_PAWN_AMOUNT      DOUBLE PRECISION,
  TRAN_INTEREST         DOUBLE PRECISION,
  PRINC_BALANCE         DOUBLE PRECISION,
  INTEREST_BALANCE      DOUBLE PRECISION,
  TRAN_TIME                         TIME         DEFAULT CURRENT_TIME,
  TRAN_CLOSE_REASON             SMALLINT         DEFAULT 0 NOT NULL,
  TRAN_SALES_TAX        DOUBLE PRECISION,
  PRIMARY KEY (TRANSACTION_NO)
);

COMMENT ON COLUMN TRANSACTIONS.TRAN_STATUS IS 'A-Active
V-Void';

COMMENT ON COLUMN TRANSACTIONS.TRAN_CLOSE_REASON IS '0-Open 1-Void 2-Redeemed 3-Defaulted 4-Mix 0-Open 1-Void 2-Redeemed 3-Defaulted 4-Mix Default/Redeem';

CREATE TABLE TRANSACTION_TYPES 
(
  TRAN_TYPE                      CHAR(1) NOT NULL,
  TRAN_TYPE_DESC              VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TRANSACTION_TYPES PRIMARY KEY (TRAN_TYPE)
);

SET TERM ^^ ;
/*******************************************************************************
 * Stored Procedure Headers
 * ------------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE PROCEDURE REP_CUSTOMER_WITH_LATE_PAYMENTS (
  MONS Integer DEFAULT 1)
 returns (
  TRANSACTION_NO Integer, 
  TRAN_TICKET_NO VarChar(30), 
  TRAN_DATE Timestamp, 
  LATE_PAYMENT SmallInt, 
  CUST_NO Integer, 
  CUST_LAST VarChar(35), 
  CUST_FIRST VarChar(35), 
  CUST_MID Char(1), 
  CUST_PH_CELL VarChar(14), 
  CUST_PH_HOME VarChar(14), 
  CUST_PH_BUSINESS VarChar(14), 
  TRAN_PAWN_AMOUNT Double Precision) AS
BEGIN
  EXIT;
END ^^

CREATE PROCEDURE SPI_GOLD_PRICE (
  PRICE_PER_OUNCE Decimal(10,2), 
  CURRENCY VarChar(3))
 returns (
  LAST_G_PRICE Decimal(10,2)) AS
BEGIN
  EXIT;
END ^^

CREATE PROCEDURE SPS_APP_STATE (
  P_STATE_KEY VarChar(50))
 returns (
  STATE_DESC VarChar(255),
  VALUE_TEXT VarChar(255),
  VALUE_INT Integer,
  VALUE_CURRENCY Numeric(18,2),
  VALUE_DATE Timestamp) AS
BEGIN
  EXIT;
END ^^

CREATE PROCEDURE SPU_APP_STATE (
  P_STATE_KEY VarChar(50),
  P_VALUE_TEXT VarChar(255),
  P_VALUE_INT Integer,
  P_VALUE_CURRENCY Numeric(18,2),
  P_VALUE_DATE Timestamp) AS
BEGIN
  EXIT;
END ^^

CREATE PROCEDURE SPU_CALC_UNIT_COST_FROM_WEIGHT (
  TRANSACTION_NO Integer) AS
BEGIN
  EXIT;
END ^^

CREATE PROCEDURE SP_CREATE_EXPORT_LOG (
  FILE_NAME VarChar(50))
 returns (
  EXPORT_LOG_ID Integer) AS
BEGIN
  EXIT;
END ^^

/*******************************************************************************
 * Stored Function Headers
 * -----------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE FUNCTION FN_TRAN_WITH_LATE_PAYMENT (
  TRANSACTION_NO Integer, 
  MONS Integer DEFAULT 1)
 RETURNS SmallInt
AS
BEGIN
  RETURN NULL;
END ^^

SET TERM ; ^^
/*******************************************************************************
 * Table Computed Columns
 * ----------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

/*******************************************************************************
 * Indices
 * -------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE ASC INDEX CUSTOMER_IDX1 ON CUSTOMER (CUST_FIRST, CUST_LAST);

CREATE ASC INDEX CUSTOMER_IDX2 ON CUSTOMER (CUST_LAST, CUST_FIRST);

CREATE ASC INDEX EXPORT_LOG_FILE_DETAIL_IDX1 ON EXPORT_LOG_FILE_DETAIL (TRANSACTION_NO);

CREATE DESC INDEX GOLD_PRICE_HISTORY_IDX1 ON GOLD_PRICE_HISTORY (FETCHDATETIME);

CREATE UNIQUE ASC INDEX IMAGES_DATA_BACKUP_IDX1 ON IMAGES_DATA_BACKUP (IMAGES_DATA_NO);

CREATE ASC INDEX IMAGES_DATA_IDX1 ON IMAGES_DATA (IMAG_REF_TO_ROW_NO);

CREATE ASC INDEX INVENTORY_ITEM_STATUS_LOG_IDX1 ON INVENTORY_ITEM_STATUS_LOG (INV_ITEM_NO, CHANGED_AT);

CREATE ASC INDEX STONES_IDX1 ON STONES (STONE_TYPE);

CREATE ASC INDEX TRANSACTIONS_IDX1 ON TRANSACTIONS (CUST_NO, TRAN_DATE, TRAN_TICKET_NO);

/*******************************************************************************
 * Foreign Key Constraints
 * -----------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

ALTER TABLE INVENTORY_ITEMS ADD CONSTRAINT FK_INVENTORY_ITEMS_TRANSACTIONS 
  FOREIGN KEY (TRANSACTION_NO) REFERENCES TRANSACTIONS
  (TRANSACTION_NO) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_TRANSACTIONS 
  FOREIGN KEY (TRANSACTION_NO) REFERENCES TRANSACTIONS
  (TRANSACTION_NO) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE STONES ADD CONSTRAINT FK_STONES_INVENTORY_ITEMS 
  FOREIGN KEY (INV_ITEM_NO) REFERENCES INVENTORY_ITEMS
  (INV_ITEM_NO) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_CUSTOMER 
  FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER
  (CUST_NO) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

SET TERM ^^ ;
/*******************************************************************************
 * Stored Procedure Bodies
 * -----------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE OR ALTER PROCEDURE REP_CUSTOMER_WITH_LATE_PAYMENTS (
  MONS Integer DEFAULT 1)
 returns (
  TRANSACTION_NO Integer, 
  TRAN_TICKET_NO VarChar(30), 
  TRAN_DATE Timestamp, 
  LATE_PAYMENT SmallInt, 
  CUST_NO Integer, 
  CUST_LAST VarChar(35), 
  CUST_FIRST VarChar(35), 
  CUST_MID Char(1), 
  CUST_PH_CELL VarChar(14), 
  CUST_PH_HOME VarChar(14), 
  CUST_PH_BUSINESS VarChar(14), 
  TRAN_PAWN_AMOUNT Double Precision)
SQL SECURITY INVOKER
AS
BEGIN
  FOR
    SELECT FIRST 1000
      T2.TRANSACTION_NO,
      T2.TRAN_TICKET_NO,
      CAST(T2.TRAN_DATE AS TIMESTAMP),
      1,
      T1.CUST_NO,
      T1.CUST_LAST,
      T1.CUST_FIRST,
      T1.CUST_MID,
      T1.CUST_PH_CELL,
      T1.CUST_PH_HOME,
      T1.CUST_PH_BUSINESS,
      T2.TRAN_PAWN_AMOUNT
    FROM CUSTOMER T1
      JOIN TRANSACTIONS T2 ON T1.CUST_NO = T2.CUST_NO
    WHERE T2.TRAN_TYPE   = 'P'
      AND T2.TRAN_STATUS = 'A'
      AND FN_TRAN_WITH_LATE_PAYMENT(T2.TRANSACTION_NO, :MONS) = 1
    ORDER BY T1.CUST_FIRST ASC, T1.CUST_LAST ASC, T1.CUST_NO ASC
    INTO
      :TRANSACTION_NO,
      :TRAN_TICKET_NO,
      :TRAN_DATE,
      :LATE_PAYMENT,
      :CUST_NO,
      :CUST_LAST,
      :CUST_FIRST,
      :CUST_MID,
      :CUST_PH_CELL,
      :CUST_PH_HOME,
      :CUST_PH_BUSINESS,
      :TRAN_PAWN_AMOUNT
  DO
    SUSPEND;
END ^^

CREATE OR ALTER PROCEDURE SPI_GOLD_PRICE (
  PRICE_PER_OUNCE Decimal(10,2), 
  CURRENCY VarChar(3))
 returns (
  LAST_G_PRICE Decimal(10,2))
SQL SECURITY INVOKER
AS
BEGIN
  LAST_G_PRICE = 0;

  SELECT FIRST 1 PRICE_PER_OUNCE
    FROM GOLD_PRICE_HISTORY
    ORDER BY PRICE_ID DESC
    INTO :LAST_G_PRICE;

  LAST_G_PRICE = COALESCE(:LAST_G_PRICE, 0);

  IF (:LAST_G_PRICE <> :PRICE_PER_OUNCE) THEN
    INSERT INTO GOLD_PRICE_HISTORY (PRICE_PER_OUNCE, CURRENCY, FETCHDATETIME, SOURCE)
      VALUES (:PRICE_PER_OUNCE, :CURRENCY, CURRENT_TIMESTAMP, 'Yahoo');

  SUSPEND;
END ^^

CREATE OR ALTER PROCEDURE SPS_APP_STATE (
  P_STATE_KEY VarChar(50))
 returns (
  STATE_DESC VarChar(255),
  VALUE_TEXT VarChar(255),
  VALUE_INT Integer,
  VALUE_CURRENCY Numeric(18,2),
  VALUE_DATE Timestamp)
SQL SECURITY INVOKER
AS
BEGIN
  FOR
    SELECT
      STATE_DESC,
      VALUE_TEXT,
      VALUE_INT,
      VALUE_CURRENCY,
      VALUE_DATE
    FROM APP_STATE
    WHERE STATE_KEY = :P_STATE_KEY
    INTO
      :STATE_DESC,
      :VALUE_TEXT,
      :VALUE_INT,
      :VALUE_CURRENCY,
      :VALUE_DATE
  DO
    SUSPEND;
END ^^

CREATE OR ALTER PROCEDURE SPU_APP_STATE (
  P_STATE_KEY VarChar(50),
  P_VALUE_TEXT VarChar(255),
  P_VALUE_INT Integer,
  P_VALUE_CURRENCY Numeric(18,2),
  P_VALUE_DATE Timestamp)
SQL SECURITY INVOKER
AS
BEGIN
  UPDATE OR INSERT INTO APP_STATE (
    STATE_KEY,
    VALUE_TEXT,
    VALUE_INT,
    VALUE_CURRENCY,
    VALUE_DATE)
  VALUES (
    :P_STATE_KEY,
    :P_VALUE_TEXT,
    :P_VALUE_INT,
    :P_VALUE_CURRENCY,
    :P_VALUE_DATE)
  MATCHING (STATE_KEY);
END ^^

CREATE OR ALTER PROCEDURE SPU_CALC_UNIT_COST_FROM_WEIGHT (
  TRANSACTION_NO Integer)
SQL SECURITY INVOKER
AS
DECLARE VARIABLE TOTAL_WEIGHT      DOUBLE PRECISION;
  DECLARE VARIABLE TOTAL_AMOUNT      DOUBLE PRECISION;
  DECLARE VARIABLE DOLLAR_PER_WEIGHT DOUBLE PRECISION;
BEGIN
  SELECT SUM(WEIGHT)       FROM INVENTORY_ITEMS WHERE TRANSACTION_NO = :TRANSACTION_NO INTO :TOTAL_WEIGHT;
  SELECT TRAN_PAWN_AMOUNT  FROM TRANSACTIONS    WHERE TRANSACTION_NO = :TRANSACTION_NO INTO :TOTAL_AMOUNT;

  DOLLAR_PER_WEIGHT = :TOTAL_AMOUNT / :TOTAL_WEIGHT;

  UPDATE INVENTORY_ITEMS
    SET UNIT_COST = :DOLLAR_PER_WEIGHT * WEIGHT
    WHERE TRANSACTION_NO = :TRANSACTION_NO;
END ^^

CREATE OR ALTER PROCEDURE SP_CREATE_EXPORT_LOG (
  FILE_NAME VarChar(50))
 returns (
  EXPORT_LOG_ID Integer)
SQL SECURITY INVOKER
AS
BEGIN
  INSERT INTO EXPORT_FILE_LOG (EXPORT_DATE, FILE_NAME)
    VALUES (CURRENT_TIMESTAMP, :FILE_NAME)
    RETURNING EXPORT_LOG_ID INTO :EXPORT_LOG_ID;
  SUSPEND;
END ^^

/*******************************************************************************
 * Stored Function Bodies
 * ----------------------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

CREATE OR ALTER FUNCTION FN_TRAN_WITH_LATE_PAYMENT  (
  TRANSACTION_NO Integer, 
  MONS Integer DEFAULT 1)
 RETURNS SmallInt
SQL SECURITY INVOKER
AS
DECLARE VARIABLE PAWN_DATE     DATE;
  DECLARE VARIABLE LAST_PAY_DAY  DATE;
  DECLARE VARIABLE CMP_DATE      DATE;
BEGIN
  SELECT TRAN_DATE       FROM TRANSACTIONS WHERE TRANSACTION_NO = :TRANSACTION_NO INTO :PAWN_DATE;
  SELECT MAX(PAY_DATE)   FROM PAYMENTS     WHERE TRANSACTION_NO = :TRANSACTION_NO INTO :LAST_PAY_DAY;

  CMP_DATE = COALESCE(:LAST_PAY_DAY, :PAWN_DATE);
  IF (:CMP_DATE IS NULL) THEN
    RETURN 0;

  IF (ABS(DATEDIFF(MONTH FROM :CMP_DATE TO CURRENT_DATE)) > :MONS) THEN
    RETURN 1;
  ELSE
    RETURN 0;
END ^^

SET TERM ; ^^
SET TERM ^^ ;
/*******************************************************************************
 * Triggers
 * --------
 * Extracted at 6/17/2026 10:32:24 AM
 ******************************************************************************/

/*******************************************************************************
 * Trigger TRG_INV_ITEMS_STATUS_LOG on table/view INVENTORY_ITEMS
 ******************************************************************************/

CREATE TRIGGER TRG_INV_ITEMS_STATUS_LOG FOR INVENTORY_ITEMS ACTIVE AFTER UPDATE POSITION 0 SQL SECURITY INVOKER AS
BEGIN
  IF (OLD.INV_ITEM_STATUS IS DISTINCT FROM NEW.INV_ITEM_STATUS
      OR OLD.PAWNED_DATE    IS DISTINCT FROM NEW.PAWNED_DATE
      OR OLD.PURCHASE_DATE  IS DISTINCT FROM NEW.PURCHASE_DATE
      OR OLD.REDEEMED_DATE  IS DISTINCT FROM NEW.REDEEMED_DATE
      OR OLD.DEFAULTED_DATE IS DISTINCT FROM NEW.DEFAULTED_DATE
      OR OLD.MELTED_DATE    IS DISTINCT FROM NEW.MELTED_DATE
      OR OLD.FORSALE_DATE   IS DISTINCT FROM NEW.FORSALE_DATE
      OR OLD.SOLD_DATE      IS DISTINCT FROM NEW.SOLD_DATE
      OR OLD.LAYAWAY_DATE   IS DISTINCT FROM NEW.LAYAWAY_DATE) THEN
  BEGIN
    INSERT INTO INVENTORY_ITEM_STATUS_LOG (
      INV_ITEM_NO,
      OLD_STATUS,         NEW_STATUS,
      OLD_PAWNED_DATE,    NEW_PAWNED_DATE,
      OLD_PURCHASE_DATE,  NEW_PURCHASE_DATE,
      OLD_REDEEMED_DATE,  NEW_REDEEMED_DATE,
      OLD_DEFAULTED_DATE, NEW_DEFAULTED_DATE,
      OLD_MELTED_DATE,    NEW_MELTED_DATE,
      OLD_FORSALE_DATE,   NEW_FORSALE_DATE,
      OLD_SOLD_DATE,      NEW_SOLD_DATE,
      OLD_LAYAWAY_DATE,   NEW_LAYAWAY_DATE,
      CHANGED_BY
    ) VALUES (
      NEW.INV_ITEM_NO,
      OLD.INV_ITEM_STATUS, NEW.INV_ITEM_STATUS,
      OLD.PAWNED_DATE,     NEW.PAWNED_DATE,
      OLD.PURCHASE_DATE,   NEW.PURCHASE_DATE,
      OLD.REDEEMED_DATE,   NEW.REDEEMED_DATE,
      OLD.DEFAULTED_DATE,  NEW.DEFAULTED_DATE,
      OLD.MELTED_DATE,     NEW.MELTED_DATE,
      OLD.FORSALE_DATE,    NEW.FORSALE_DATE,
      OLD.SOLD_DATE,       NEW.SOLD_DATE,
      OLD.LAYAWAY_DATE,    NEW.LAYAWAY_DATE,
      CURRENT_USER
    );
  END
END
 ^^

SET TERM ; ^^
