/*******************************************************************************
 * PawnPro - Firebird 5 Multilanguage Database Foundation
 * REVIEW DRAFT - NOT YET INTEGRATED OR DEPLOYED
 * -----------------------------------------------------------------------------
 * This standalone script is for design review and isolated validation only.
 * It is intentionally not referenced by:
 *   - Schema/PawnPro_DB_Firebird50_Schema.sql
 *   - Schema/PawnPro_FB5_NewStoreFullDeploy.sql
 *   - uDBMigrations.pas
 *
 * After approval, this DDL will be converted into the canonical migration and
 * synchronized with all three integration targets above.
 *
 * Contents:
 *   1. ML_LANGUAGES, ML_LANG_OBJECTS, ML_LANG_VALUES tables
 *   2. Language-first loading index
 *   3. ML_LANG_VALUES update-timestamp trigger
 *   4. GET_LANG_TEXT lookup-overlay function
 *   5. SPU_LANG_UPSERT natural-key upsert procedure
 *   6. SPD_LANG_DELETE natural-key delete procedure
 *   7. English and Spanish language seeds
 *
 * Important ownership rules:
 *   - Stored business codes are never translated.
 *   - Form/literal English and translations live in ML_LANG_VALUES.
 *   - Lookup English remains canonical in its base *_DESC column.
 *   - ML_LANG_VALUES stores only non-English overlays for lookup objects.
 *   - A missing translation is represented by no ML_LANG_VALUES row.
 *   - Empty/whitespace-only translation rows are rejected.
 ******************************************************************************/


/* ---------------------------------------------------------------------------
 * 1. Supported languages
 * ------------------------------------------------------------------------ */

CREATE TABLE ML_LANGUAGES
(
  LANGUAGE_ID  VARCHAR(5)  CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  NAME         VARCHAR(50) CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  IS_ACTIVE    SMALLINT DEFAULT 1 NOT NULL,

  CONSTRAINT PK_ML_LANGUAGES PRIMARY KEY (LANGUAGE_ID),
  CONSTRAINT CK_ML_LANGUAGES_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);


/* ---------------------------------------------------------------------------
 * 2. One row per translatable atom
 *
 * Natural identity is (OBJECT_TYPE, OBJ_NAME, ITEM_KEY). OBJECT_ID is an
 * internal database identity only and must never appear in portable migration
 * content or JSON snapshots.
 * ------------------------------------------------------------------------ */

CREATE TABLE ML_LANG_OBJECTS
(
  OBJECT_ID     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  OBJECT_TYPE   VARCHAR(10)  CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  OBJ_NAME      VARCHAR(80)  CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  ITEM_KEY      VARCHAR(255) CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  IS_FORMAT     SMALLINT DEFAULT 0 NOT NULL,
  IS_EXTRACTED  SMALLINT DEFAULT 0 NOT NULL,
  DISPLAY_NAME  VARCHAR(160) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,

  CONSTRAINT PK_ML_LANG_OBJECTS PRIMARY KEY (OBJECT_ID),
  CONSTRAINT UQ_ML_LANG_OBJECTS_NATURAL
    UNIQUE (OBJECT_TYPE, OBJ_NAME, ITEM_KEY),
  CONSTRAINT CK_ML_LANG_OBJECTS_TYPE
    CHECK (OBJECT_TYPE IN ('form', 'literal', 'lookup')),
  CONSTRAINT CK_ML_LANG_OBJECTS_FORMAT CHECK (IS_FORMAT IN (0, 1)),
  CONSTRAINT CK_ML_LANG_OBJECTS_EXTRACTED CHECK (IS_EXTRACTED IN (0, 1)),
  CONSTRAINT CK_ML_LANG_OBJECTS_NAME
    CHECK (CHAR_LENGTH(TRIM(OBJ_NAME)) > 0),
  CONSTRAINT CK_ML_LANG_OBJECTS_KEY
    CHECK (CHAR_LENGTH(TRIM(ITEM_KEY)) > 0)
);


/* ---------------------------------------------------------------------------
 * 3. One row per atom/language value
 * ------------------------------------------------------------------------ */

CREATE TABLE ML_LANG_VALUES
(
  OBJECT_ID     INTEGER NOT NULL,
  LANGUAGE_ID   VARCHAR(5)   CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  TEXT_VALUE    VARCHAR(500) CHARACTER SET UTF8 NOT NULL COLLATE UNICODE_CI_AI,
  NEEDS_REVIEW  SMALLINT DEFAULT 0 NOT NULL,
  UPDATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

  CONSTRAINT PK_ML_LANG_VALUES PRIMARY KEY (OBJECT_ID, LANGUAGE_ID),
  CONSTRAINT FK_ML_LANG_VALUES_OBJECT FOREIGN KEY (OBJECT_ID)
    REFERENCES ML_LANG_OBJECTS (OBJECT_ID)
    ON DELETE CASCADE,
  CONSTRAINT FK_ML_LANG_VALUES_LANGUAGE FOREIGN KEY (LANGUAGE_ID)
    REFERENCES ML_LANGUAGES (LANGUAGE_ID),
  CONSTRAINT CK_ML_LANG_VALUES_REVIEW CHECK (NEEDS_REVIEW IN (0, 1)),
  CONSTRAINT CK_ML_LANG_VALUES_TEXT
    CHECK (CHAR_LENGTH(TRIM(TEXT_VALUE)) > 0)
);


/* Startup loads values by language. The PK already covers object-first access. */
CREATE ASC INDEX IX_ML_LANG_VALUES_LANGUAGE
  ON ML_LANG_VALUES (LANGUAGE_ID, OBJECT_ID);


SET TERM ^^ ;


/* ---------------------------------------------------------------------------
 * 4. Keep UPDATED_AT correct for optimistic editor concurrency
 * ------------------------------------------------------------------------ */

CREATE OR ALTER TRIGGER TRG_ML_LANG_VALUES_BU FOR ML_LANG_VALUES
ACTIVE BEFORE UPDATE POSITION 0
SQL SECURITY INVOKER
AS
BEGIN
  NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END ^^


/* ---------------------------------------------------------------------------
 * 5. Resolve a non-English database lookup overlay
 *
 * Returns NULL when no overlay exists. The caller COALESCEs this result to the
 * canonical English base-table description.
 * ------------------------------------------------------------------------ */

CREATE OR ALTER FUNCTION GET_LANG_TEXT
(
  AOBJ_NAME  VARCHAR(80)  CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  AITEM_KEY  VARCHAR(255) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  ALANG      VARCHAR(5)   CHARACTER SET UTF8 COLLATE UNICODE_CI_AI
)
RETURNS VARCHAR(500) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI
SQL SECURITY INVOKER
AS
DECLARE VARIABLE V_TEXT VARCHAR(500) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI;
BEGIN
  V_TEXT = NULL;

  SELECT V.TEXT_VALUE
    FROM ML_LANG_VALUES V
    JOIN ML_LANG_OBJECTS O ON O.OBJECT_ID = V.OBJECT_ID
   WHERE O.OBJECT_TYPE = 'lookup'
     AND O.OBJ_NAME = :AOBJ_NAME
     AND O.ITEM_KEY = TRIM(:AITEM_KEY)
     AND V.LANGUAGE_ID = :ALANG
    ROWS 1
    INTO :V_TEXT;

  RETURN V_TEXT;
END ^^


/* ---------------------------------------------------------------------------
 * 6. Idempotent natural-key object/value upsert
 *
 * Signature intentionally contains portable natural values only:
 *   object_type, obj_name, item_key, is_format, language_id, text_value
 *
 * When canonical English changes, existing non-English values are retained and
 * marked NEEDS_REVIEW=1. Upserting a shipped value clears its own review flag.
 * ------------------------------------------------------------------------ */

CREATE OR ALTER PROCEDURE SPU_LANG_UPSERT
(
  P_OBJECT_TYPE  VARCHAR(10)  CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_OBJ_NAME     VARCHAR(80)  CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_ITEM_KEY     VARCHAR(255) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_IS_FORMAT    SMALLINT,
  P_LANGUAGE_ID  VARCHAR(5)   CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_TEXT_VALUE   VARCHAR(500) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI
)
SQL SECURITY INVOKER
AS
DECLARE VARIABLE V_OBJECT_ID INTEGER;
DECLARE VARIABLE V_OLD_TEXT VARCHAR(500) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI;
DECLARE VARIABLE V_IS_EXTRACTED SMALLINT;
BEGIN
  IF (:P_OBJECT_TYPE = 'form') THEN
    V_IS_EXTRACTED = 1;
  ELSE
    V_IS_EXTRACTED = 0;

  UPDATE OR INSERT INTO ML_LANG_OBJECTS
    (OBJECT_TYPE, OBJ_NAME, ITEM_KEY, IS_FORMAT, IS_EXTRACTED)
  VALUES
    (:P_OBJECT_TYPE, :P_OBJ_NAME, :P_ITEM_KEY, :P_IS_FORMAT, :V_IS_EXTRACTED)
  MATCHING (OBJECT_TYPE, OBJ_NAME, ITEM_KEY)
  RETURNING OBJECT_ID INTO :V_OBJECT_ID;

  V_OLD_TEXT = NULL;

  SELECT TEXT_VALUE
    FROM ML_LANG_VALUES
   WHERE OBJECT_ID = :V_OBJECT_ID
     AND LANGUAGE_ID = :P_LANGUAGE_ID
    INTO :V_OLD_TEXT;

  UPDATE OR INSERT INTO ML_LANG_VALUES
    (OBJECT_ID, LANGUAGE_ID, TEXT_VALUE, NEEDS_REVIEW)
  VALUES
    (:V_OBJECT_ID, :P_LANGUAGE_ID, :P_TEXT_VALUE, 0)
  MATCHING (OBJECT_ID, LANGUAGE_ID);

  IF (:P_LANGUAGE_ID = 'en'
      AND :V_OLD_TEXT IS DISTINCT FROM :P_TEXT_VALUE) THEN
    UPDATE ML_LANG_VALUES
       SET NEEDS_REVIEW = 1
     WHERE OBJECT_ID = :V_OBJECT_ID
       AND LANGUAGE_ID <> 'en';
END ^^


/* ---------------------------------------------------------------------------
 * 7. Idempotent whole-object delete by portable natural key
 *
 * ML_LANG_VALUES children are removed by FK_ML_LANG_VALUES_OBJECT ON DELETE
 * CASCADE.
 * Deleting an already-absent object is a successful no-op.
 * ------------------------------------------------------------------------ */

CREATE OR ALTER PROCEDURE SPD_LANG_DELETE
(
  P_OBJECT_TYPE  VARCHAR(10)  CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_OBJ_NAME     VARCHAR(80)  CHARACTER SET UTF8 COLLATE UNICODE_CI_AI,
  P_ITEM_KEY     VARCHAR(255) CHARACTER SET UTF8 COLLATE UNICODE_CI_AI
)
SQL SECURITY INVOKER
AS
BEGIN
  DELETE FROM ML_LANG_OBJECTS
   WHERE OBJECT_TYPE = :P_OBJECT_TYPE
     AND OBJ_NAME = :P_OBJ_NAME
     AND ITEM_KEY = :P_ITEM_KEY;
END ^^


SET TERM ; ^^


/* ---------------------------------------------------------------------------
 * 8. Initial language rows only
 *
 * Translation atoms/values will be generated after the scanner/editor exists;
 * they are intentionally not hand-authored in this structure script.
 * ------------------------------------------------------------------------ */

UPDATE OR INSERT INTO ML_LANGUAGES (LANGUAGE_ID, NAME, IS_ACTIVE)
VALUES ('en', 'English', 1)
MATCHING (LANGUAGE_ID);

UPDATE OR INSERT INTO ML_LANGUAGES (LANGUAGE_ID, NAME, IS_ACTIVE)
VALUES ('es', 'Español', 1)
MATCHING (LANGUAGE_ID);


COMMIT;


/*******************************************************************************
 * Example only - not executed:
 *
 * SELECT STATUS,
 *        COALESCE(
 *          GET_LANG_TEXT('ITEM_STATUS', STATUS, 'es'),
 *          STATUS_DESC
 *        ) AS STATUS_DESC
 *   FROM ITEM_STATUS
 *  ORDER BY 2;
 ******************************************************************************/
