/*******************************************************************************
 * PawnPro — Firebird 5 additions to close the gap with SQL Anywhere 16
 *
 * Run once against an existing FB5 PawnPro database. Safe to re-run only if
 * you first drop the objects it creates; there is no IF NOT EXISTS guarding.
 *
 * Contents:
 *   1. New audit-log table INVENTORY_ITEM_STATUS_LOG (+ its index)
 *      NOTE: the trigger that populates this table is NOT included here;
 *            port it separately from ASA's trg_InvItems_StatusLog.
 *   2. Missing foreign key TRANSACTIONS.CUST_NO -> CUSTOMER.CUST_NO
 *   3. Missing performance indexes
 *
 * Indexes that Firebird auto-creates for FK columns are intentionally skipped:
 *   - TRANSACTIONS(CUST_NO)         -> created by FK_TRANSACTIONS_CUSTOMER
 *   - INVENTORY_ITEMS(TRANSACTION_NO) -> created by FK_INVENTORY_ITEMS_TRANSACTIONS
 *   - PAYMENTS(TRANSACTION_NO)      -> created by FK_PAYMENTS_TRANSACTIONS
 *   - STONES(INV_ITEM_NO)           -> created by FK_STONES_INVENTORY_ITEMS
 ******************************************************************************/


/* ---------------------------------------------------------------------------
 * 1. Audit-log table
 * ------------------------------------------------------------------------ */

CREATE TABLE INVENTORY_ITEM_STATUS_LOG
(
  LOG_ID                   BIGINT         GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
  INV_ITEM_NO             INTEGER         NOT NULL,
  OLD_STATUS                 CHAR(1),
  NEW_STATUS                 CHAR(1)      NOT NULL,
  OLD_PAWNED_DATE               DATE,
  NEW_PAWNED_DATE               DATE,
  OLD_PURCHASE_DATE             DATE,
  NEW_PURCHASE_DATE             DATE,
  OLD_REDEEMED_DATE             DATE,
  NEW_REDEEMED_DATE             DATE,
  OLD_DEFAULTED_DATE            DATE,
  NEW_DEFAULTED_DATE            DATE,
  OLD_MELTED_DATE               DATE,
  NEW_MELTED_DATE               DATE,
  OLD_FORSALE_DATE              DATE,
  NEW_FORSALE_DATE              DATE,
  OLD_SOLD_DATE                 DATE,
  NEW_SOLD_DATE                 DATE,
  OLD_LAYAWAY_DATE              DATE,
  NEW_LAYAWAY_DATE              DATE,
  CHANGED_BY               VARCHAR(50),
  CHANGED_AT             TIMESTAMP         DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_INVENTORY_ITEM_STATUS_LOG PRIMARY KEY (LOG_ID)
);

CREATE ASC INDEX INVENTORY_ITEM_STATUS_LOG_IDX1
  ON INVENTORY_ITEM_STATUS_LOG (INV_ITEM_NO, CHANGED_AT);


/* ---------------------------------------------------------------------------
 * 2. Missing foreign key
 * ------------------------------------------------------------------------ */

ALTER TABLE TRANSACTIONS ADD CONSTRAINT FK_TRANSACTIONS_CUSTOMER
  FOREIGN KEY (CUST_NO) REFERENCES CUSTOMER (CUST_NO)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;


/* ---------------------------------------------------------------------------
 * 3. Missing performance indexes
 * ------------------------------------------------------------------------ */

CREATE ASC INDEX CUSTOMER_IDX2
  ON CUSTOMER (CUST_LAST, CUST_FIRST);

CREATE ASC INDEX TRANSACTIONS_IDX1
  ON TRANSACTIONS (CUST_NO, TRAN_DATE, TRAN_TICKET_NO);

CREATE ASC INDEX INVENTORY_ITEMS_IDX1
  ON INVENTORY_ITEMS (INV_ITEM_BARCODE);

CREATE ASC INDEX INVENTORY_ITEMS_IDX2
  ON INVENTORY_ITEMS (INV_ITEM_BRAND);

CREATE ASC INDEX STONES_IDX1
  ON STONES (STONE_TYPE);

CREATE ASC INDEX EXPORT_LOG_FILE_DETAIL_IDX1
  ON EXPORT_LOG_FILE_DETAIL (TRANSACTION_NO);

CREATE ASC INDEX IMAGES_DATA_IDX1
  ON IMAGES_DATA (IMAG_REF_TO_ROW_NO);

CREATE UNIQUE ASC INDEX IMAGES_DATA_BACKUP_IDX1
  ON IMAGES_DATA_BACKUP (IMAGES_DATA_NO);

CREATE DESC INDEX GOLD_PRICE_HISTORY_IDX1
  ON GOLD_PRICE_HISTORY (FETCHDATETIME);

COMMIT;
