/*******************************************************************************
 * PawnPro — Firebird 5 migration: LEADS_SOAP_IMAGE_SENT
 *
 * Records every image uploaded to LeadsOnline over SOAP.
 *
 * Deferred from the LeadsOnlineSoap migration on purpose: the column that makes
 * this table worth having is SERVER_FILENAME, and its meaning was unverified
 * until the vendor spec could be read. It is confirmed now — UploadImage
 * returns, in Response.errorResponse, "a unique name for the image created on
 * the LeadsOnline server ... can be used to delete the image if necessary using
 * the DeleteImage web service method". Without it, an image sent in error can
 * never be withdrawn.
 *
 * Keyed by (TRANSACTION_NO, IMAGES_DATA_NO) rather than by image alone, for the
 * same reason EXPORT_IMAGE_SENT exists on the FTP side: a customer ID photo is
 * ONE IMAGES_DATA row shared by every transaction that customer has, so
 * "uploaded for ticket A but not ticket B" has to be representable. Item
 * pictures belong to a single item and would not need it; customer photos do.
 *
 * ITEM_INDEX is LeadsOnline's 0-based position of the item WITHIN THE TICKET AS
 * SENT — not INV_ITEM_NO. It is only meaningful for category 'Item'. It is
 * recorded because it is part of how the image is addressed on their side, and
 * recomputing it later from a changed item list would point at the wrong item.
 *
 * Idempotent: safe to re-run.
 ******************************************************************************/

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS
                  WHERE RDB$RELATION_NAME = 'LEADS_SOAP_IMAGE_SENT')) THEN
    EXECUTE STATEMENT
      'CREATE TABLE LEADS_SOAP_IMAGE_SENT
       (
         ID               INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
         TRANSACTION_NO   INTEGER      NOT NULL,
         IMAGES_DATA_NO   INTEGER      NOT NULL,
         IMAGE_CATEGORY   VARCHAR(20)  NOT NULL,
         ITEM_INDEX       INTEGER,
         SERVER_FILENAME  VARCHAR(255),
         UPLOADED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
         ERROR_CODE       INTEGER,
         ERROR_RESPONSE   VARCHAR(500),
         CONSTRAINT PK_LEADS_SOAP_IMAGE_SENT PRIMARY KEY (ID),
         CONSTRAINT UQ_LEADS_SOAP_IMAGE_SENT UNIQUE (TRANSACTION_NO, IMAGES_DATA_NO)
       )';
END^

SET TERM ; ^
