/*******************************************************************************
 * PawnPro — Firebird 5 migration: LeadsOnline SOAP export channel
 *
 * Adds the settings a store needs to talk to LeadsOnline's ticketWS SOAP
 * service, plus the log that remembers what was submitted.
 *
 * STORE gains four columns:
 *
 *   LEADS_ONLINE_API_USER       the API login — NOT the FTP login. LeadsOnline
 *   LEADS_ONLINE_API_PASSWORD   issue these separately from the FTP credentials
 *                               already in LEADS_ONLINE_USER_NAME / _PASSWORD.
 *   LEADS_ONLINE_EXPORT_METHOD  'C' = CSV over FTP (today), 'S' = SOAP.
 *                               Defaults to 'C', which is what makes this
 *                               migration purely additive: every existing store
 *                               keeps its current behaviour until someone
 *                               deliberately switches it over.
 *   LEADS_ONLINE_USE_SANDBOX    route to LeadsOnline's sandbox host instead of
 *                               production. Defaults to FALSE.
 *
 * There is deliberately no LEADS_ONLINE_API_STORE_ID. STORE.LEADS_STORE_ID
 * already holds LeadsOnline's store number — the CSV path uses it to build image
 * filenames — and it is the same value the SOAP LoginInfo.storeId needs. A
 * second copy would only be a second thing to get out of step.
 *
 * The password is stored in clear text, exactly as the FTP password beside it
 * already is. Encrypting both is a separate, deliberate pass; the column is
 * sized VARCHAR(255) now so that pass does not also need a widening migration.
 *
 * LEADS_SOAP_SUBMISSION records what was sent. SOAP assigns no server-side
 * ticket id, so the only handle on a submitted ticket is the composite key we
 * transmitted (ticketType + ticketnumber + ticketDateTime). It is stored here
 * VERBATIM, as sent: if a ticket number or date is later edited in PawnPro,
 * recomputing the key from current data would address a ticket LeadsOnline has
 * never heard of, and UpdateTransaction could never find the original again.
 *
 * The image log (LEADS_SOAP_IMAGE_SENT) is NOT created here. Its central column
 * is the server-assigned filename returned in Response.errorResponse, and that
 * semantic is not verified yet — it lands with the image phase rather than being
 * guessed at now.
 *
 * Idempotent: safe to re-run. Every object is created only if absent, and the
 * backfills are guarded on IS NULL.
 ******************************************************************************/

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS
                  WHERE RDB$RELATION_NAME = 'STORE'
                    AND RDB$FIELD_NAME = 'LEADS_ONLINE_API_USER')) THEN
    EXECUTE STATEMENT
      'ALTER TABLE STORE ADD LEADS_ONLINE_API_USER VARCHAR(50)';

  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS
                  WHERE RDB$RELATION_NAME = 'STORE'
                    AND RDB$FIELD_NAME = 'LEADS_ONLINE_API_PASSWORD')) THEN
    EXECUTE STATEMENT
      'ALTER TABLE STORE ADD LEADS_ONLINE_API_PASSWORD VARCHAR(255)';

  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS
                  WHERE RDB$RELATION_NAME = 'STORE'
                    AND RDB$FIELD_NAME = 'LEADS_ONLINE_EXPORT_METHOD')) THEN
    EXECUTE STATEMENT
      'ALTER TABLE STORE ADD LEADS_ONLINE_EXPORT_METHOD CHAR(1) DEFAULT ''C''';

  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATION_FIELDS
                  WHERE RDB$RELATION_NAME = 'STORE'
                    AND RDB$FIELD_NAME = 'LEADS_ONLINE_USE_SANDBOX')) THEN
    EXECUTE STATEMENT
      'ALTER TABLE STORE ADD LEADS_ONLINE_USE_SANDBOX BOOLEAN DEFAULT FALSE';
END^

/* Commit the DDL before anything reads the new columns. Without this the
   backfill below runs in the same transaction that created them, cannot see
   them, and fails with "Column unknown" — leaving every existing store on NULL
   until the script happened to be run a second time. */
COMMIT^

/* Firebird does not backfill existing rows when a column is added with a
   DEFAULT — the default applies to future inserts. Existing stores would read
   NULL, so set them explicitly. Run dynamically: the columns do not exist at
   the time this block is compiled on a store that has not been migrated yet. */
EXECUTE BLOCK AS
BEGIN
  EXECUTE STATEMENT
    'UPDATE STORE SET LEADS_ONLINE_EXPORT_METHOD = ''C''
      WHERE LEADS_ONLINE_EXPORT_METHOD IS NULL';

  EXECUTE STATEMENT
    'UPDATE STORE SET LEADS_ONLINE_USE_SANDBOX = FALSE
      WHERE LEADS_ONLINE_USE_SANDBOX IS NULL';
END^

COMMIT^

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS
                  WHERE RDB$RELATION_NAME = 'LEADS_SOAP_SUBMISSION')) THEN
    EXECUTE STATEMENT
      'CREATE TABLE LEADS_SOAP_SUBMISSION
       (
         ID               INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
         TRANSACTION_NO   INTEGER      NOT NULL,
         TICKET_TYPE      VARCHAR(20)  NOT NULL,
         TICKET_NUMBER    VARCHAR(50)  NOT NULL,
         TICKET_DATETIME  VARCHAR(30)  NOT NULL,
         SUBMITTED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
         ERROR_CODE       INTEGER,
         ERROR_RESPONSE   VARCHAR(500),
         IS_VOID          BOOLEAN      DEFAULT FALSE NOT NULL,
         CONSTRAINT PK_LEADS_SOAP_SUBMISSION PRIMARY KEY (ID),
         CONSTRAINT UQ_LEADS_SOAP_SUBMISSION UNIQUE (TRANSACTION_NO)
       )';
END^

SET TERM ; ^
