/*******************************************************************************
 * Add child foreign keys that point to TRANSACTIONS.
 *
 * Run after Pump_ASA_FB has loaded TRANSACTIONS, INVENTORY_ITEMS, and PAYMENTS.
 * Firebird validates existing child rows when adding a foreign key, so these
 * constraints will fail if child rows point to missing TRANSACTION_NO values.
 ******************************************************************************/

/* Optional checks. Both counts should be 0 before adding the constraints. */
SELECT COUNT(*) AS MISSING_INVENTORY_TRANSACTION
FROM INVENTORY_ITEMS I
LEFT JOIN TRANSACTIONS T ON T.TRANSACTION_NO = I.TRANSACTION_NO
WHERE I.TRANSACTION_NO IS NOT NULL
  AND T.TRANSACTION_NO IS NULL;

SELECT COUNT(*) AS MISSING_PAYMENT_TRANSACTION
FROM PAYMENTS P
LEFT JOIN TRANSACTIONS T ON T.TRANSACTION_NO = P.TRANSACTION_NO
WHERE P.TRANSACTION_NO IS NOT NULL
  AND T.TRANSACTION_NO IS NULL;

ALTER TABLE INVENTORY_ITEMS ADD CONSTRAINT FK_INVENTORY_ITEMS_TRANSACTIONS
  FOREIGN KEY (TRANSACTION_NO) REFERENCES TRANSACTIONS
  (TRANSACTION_NO)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_TRANSACTIONS
  FOREIGN KEY (TRANSACTION_NO) REFERENCES TRANSACTIONS
  (TRANSACTION_NO)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

COMMIT;
