/*******************************************************************************
 * PawnPro — Firebird 5 migration: EXPORT_IMAGE_SENT tracking table
 *
 * Tracks LeadsOnline "transaction images" (customer ID photos) that are sent
 * once PER TRANSACTION. A customer ID photo is a single IMAGES_DATA row shared
 * across all of that customer's transactions, and a LeadsOnline transaction
 * image filename embeds ONE ticket number — so the same photo is uploaded once
 * per ticket, each named with that ticket's number. The shared
 * IMAGES_DATA.UPLOAD_TIME cannot represent "sent for ticket A but not ticket B",
 * so those sends are logged here, keyed by (TRANSACTION_NO, IMAGES_DATA_NO).
 *
 * Item images keep using IMAGES_DATA.UPLOAD_TIME (unchanged) — one image row
 * maps to exactly one item in one transaction, so per-row dedup is sufficient.
 *
 * Idempotent: safe to re-run. Table is created only if it does not exist.
 ******************************************************************************/

SET TERM ^ ;

EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS (SELECT 1 FROM RDB$RELATIONS
                  WHERE RDB$RELATION_NAME = 'EXPORT_IMAGE_SENT')) THEN
    EXECUTE STATEMENT
      'CREATE TABLE EXPORT_IMAGE_SENT
       (
         ID                INTEGER      GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
         TRANSACTION_NO    INTEGER      NOT NULL,
         IMAGES_DATA_NO    INTEGER      NOT NULL,
         UPLOAD_TIME       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
         UPLOAD_FILE_NAME  VARCHAR(50),
         CONSTRAINT PK_EXPORT_IMAGE_SENT PRIMARY KEY (ID),
         CONSTRAINT UQ_EXPORT_IMAGE_SENT UNIQUE (TRANSACTION_NO, IMAGES_DATA_NO)
       )';
END^

SET TERM ; ^

COMMIT;
