program GenerateVendorKeypair;

// One-shot vendor-keypair generator for PawnPro's recovery envelope system.
//
// Run this ONCE on the developer's machine, ever. It produces:
//   vendor_public.key    32-byte Curve25519 public key (raw binary)
//   vendor_secret.key    32-byte Curve25519 secret key (raw binary)
//   SetupVendorPublicKey.inc   ready-to-paste Pascal const for the public key
//
// Workflow:
//   1. Place libsodium.dll next to this EXE.
//   2. Run it from an empty folder.
//   3. Copy SetupVendorPublicKey.inc into c:\ProjectsGIT\PawnProFB\PawnProSetup\
//      so PawnProSetup.exe has the public key embedded.
//   4. Move vendor_secret.key to an offline vault (encrypted USB, KeePass
//      attachment, etc.). DELETE the on-disk copy after moving. NEVER commit.
//   5. vendor_public.key can be kept anywhere -- it's public.
//
// If a key file already exists in the current folder, the tool refuses to
// overwrite. This is intentional: regenerating the keypair would orphan
// every recovery.dat ever shipped to a customer.

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.Classes,
  SealedBox in '..\..\COMMON\SealedBox.pas';

const
  PUB_KEY_FILE    = 'vendor_public.key';
  SECRET_KEY_FILE = 'vendor_secret.key';
  INC_FILE        = 'SetupVendorPublicKey.inc';

procedure WriteBytesToFile(const FileName: string; const B: TBytes);
var
  FS: TFileStream;
begin
  FS := TFileStream.Create(FileName, fmCreate or fmShareExclusive);
  try
    if Length(B) > 0 then
      FS.WriteBuffer(B[0], Length(B));
  finally
    FS.Free;
  end;
end;

procedure WritePubKeyInclude(const FileName: string; const PubKey: TBytes);
var
  SL: TStringList;
  I: Integer;
  Line: string;
begin
  SL := TStringList.Create;
  try
    SL.Add('// Generated by Tools\GenerateVendorKeypair.exe -- do not hand-edit.');
    SL.Add('// 32-byte Curve25519 public key used by PawnProSetup to seal');
    SL.Add('// recovery envelopes for the offline vendor secret key.');
    SL.Add('');
    SL.Add('const');
    SL.Add('  VENDOR_PUBLIC_KEY: array[0..31] of Byte = (');

    Line := '    ';
    for I := 0 to High(PubKey) do
    begin
      Line := Line + Format('$%2.2x', [PubKey[I]]);
      if I < High(PubKey) then
        Line := Line + ', ';
      // Wrap at 8 bytes per line for readability.
      if ((I + 1) mod 8 = 0) and (I < High(PubKey)) then
      begin
        SL.Add(Line);
        Line := '    ';
      end;
    end;
    if Trim(Line) <> '' then
      SL.Add(Line);

    SL.Add('  );');
    SL.SaveToFile(FileName);
  finally
    SL.Free;
  end;
end;

procedure Run;
var
  PubKey, SecretKey: TBytes;
begin
  Writeln('PawnPro vendor keypair generator');
  Writeln('--------------------------------');
  Writeln('');

  if FileExists(PUB_KEY_FILE) or FileExists(SECRET_KEY_FILE) or FileExists(INC_FILE) then
  begin
    Writeln('ERROR: One or more output files already exist in this folder:');
    if FileExists(PUB_KEY_FILE)    then Writeln('  ' + PUB_KEY_FILE);
    if FileExists(SECRET_KEY_FILE) then Writeln('  ' + SECRET_KEY_FILE);
    if FileExists(INC_FILE)        then Writeln('  ' + INC_FILE);
    Writeln('');
    Writeln('Refusing to overwrite. Regenerating the keypair would orphan every');
    Writeln('recovery.dat ever shipped to a customer. If you really mean to');
    Writeln('regenerate, MOVE the existing files away first.');
    Halt(1);
  end;

  Writeln('Generating Curve25519 keypair via libsodium...');
  if not GenerateKeypair(PubKey, SecretKey) then
  begin
    Writeln('ERROR: GenerateKeypair failed.');
    Halt(2);
  end;

  Writeln('Writing files...');
  WriteBytesToFile(PUB_KEY_FILE, PubKey);
  Writeln('  ' + PUB_KEY_FILE + ' (' + IntToStr(Length(PubKey)) + ' bytes)');
  WriteBytesToFile(SECRET_KEY_FILE, SecretKey);
  Writeln('  ' + SECRET_KEY_FILE + ' (' + IntToStr(Length(SecretKey)) + ' bytes)');
  WritePubKeyInclude(INC_FILE, PubKey);
  Writeln('  ' + INC_FILE);

  Writeln('');
  Writeln('NEXT STEPS:');
  Writeln('  1. Copy ' + INC_FILE + ' to');
  Writeln('     c:\ProjectsGIT\PawnProFB\PawnProSetup\');
  Writeln('  2. Move ' + SECRET_KEY_FILE + ' to your offline vault.');
  Writeln('     DELETE the on-disk copy in this folder after the move.');
  Writeln('  3. ' + PUB_KEY_FILE + ' can stay or be discarded -- it is now embedded');
  Writeln('     in PawnProSetup.exe via the .inc file.');
  Writeln('  4. NEVER commit either .key file to git.');
end;

begin
  try
    Run;
    Halt(0);
  except
    on E: Exception do
    begin
      Writeln(Format('ERROR: [%s] %s', [E.ClassName, E.Message]));
      Halt(10);
    end;
  end;
end.
